from pathlib import Path


HARNESS_LOGIC_DIR = Path(__file__).resolve().parent
DEFAULT_HARNESS_ROOT = HARNESS_LOGIC_DIR / "data"
DEFAULT_CHARACTER_SYSTEM_ROOT = HARNESS_LOGIC_DIR / "character_system"
DEFAULT_CHARACTER_EVIDENCE_ROOT = HARNESS_LOGIC_DIR / "data" / "novel_test"
DEFAULT_PREDICT_LENGTH = 1024
MODEL_SUBDIR = "models"
MIN_IMAGE_SLICE = 1
MAX_IMAGE_SLICE = 9
DEFAULT_IMAGE_SLICE = MAX_IMAGE_SLICE
